package edu.hw1;
    /**
     * Task5: Checks if a number is a palindrome or has a palindrome descendant.
     */
    public class Task5 {

        /**
         * Determines if the given string is a palindrome.
         *
         * @param s the input string
         * @return true if the string is a palindrome; otherwise false
         */
        private static boolean isPalindrome(String s) {
            int left = 0;
            int right = s.length() - 1;

            while (left < right) {
                if (s.charAt(left) != s.charAt(right)) {
                    return false;
                }
                left++;
                right--;
            }

            return true;
        }

        /**
         * Checks if a number is a palindrome or has a palindrome descendant.
         * A descendant is generated by summing adjacent digits.
         *
         * @param num the input number to check
         * @return true if the number or its descendants are palindromes
         */
        public static boolean isPalindromeDescendant(int num) {
            String numStr = Integer.toString(num);

            while (numStr.length() > 1) {
                if (isPalindrome(numStr)) {
                    return true;
                }

                StringBuilder descendant = new StringBuilder();
                for (int i = 0; i < numStr.length() - 1; i += 2) {
                    int sum = Character.getNumericValue(numStr.charAt(i))
                        + Character.getNumericValue(numStr.charAt(i + 1));
                    descendant.append(sum);
                }

                numStr = descendant.toString();
            }

            return false;
        }

        /**
         * Main method to test the isPalindromeDescendant method.
         *
         * @param args command-line arguments
         */
        public static void main(String[] args) {
            System.out.println(isPalindromeDescendant(23336014)); // true
            System.out.println(isPalindromeDescendant(12));       // false
        }
    }
